### ISSUE TITLE
Created Account on OpenWeather Site, API Key reports Authentication required

### ISSUE THREAD

**Issue by mushroomnz** [FelixdelasPozas/TrayWeather#12]
![TrayWeather_2020-11-07_20-24-48](https://user-images.githubusercontent.com/45083949/98434777-92846480-2137-11eb-8f7e-31c39f7b91aa.png)

When providing a API key from OpenWeather I am unable to test the key, I have created a second API key and get the same result, I also tried running app as Admin and hasn't assisted. I have checked my AV (Bit Defender) and it's not reporting any blocking or stopping

I have a Windows 10 computer, running Version 2004.
![TrayWeather_2020-11-07_20-30-28](https://user-images.githubusercontent.com/45083949/98434983-1b9b9b80-2138-11eb-92b4-98accc3f9353.png)

**Comment by FelixdelasPozas** [comment]
Hi.
I'm gonna need more details, as the current version seems to be working for everyone. 

If the key were invalid the message should be **"Invalid OpenWeatherMap API Key."**. Because the message is **"Invalid reply from OpenWeatherMap server"** it seems to be a network error. 

Either the program or your computer doesn't have access the OpenWeatherMap server without authorization? Maybe you're behind a firewall? Or a proxy?

Try this: open your browser and in a new tab enter this web address: 
**http://api.openweathermap.org/data/2.5/weather?lat=0&lon=0&appid=apikey**
Substitute **apikey** for your valid OpenWeatherMap key. Hit enter and your browser should show the OpenWeatherMap server response. 

If everything is fine it will give you the weather on [null island](https://es.wikipedia.org/wiki/Null_Island). Firefox will give you a nice looking view of the JSON, and Chrome will just dump the text response, that is the raw JSON response. If anyting else shows up, it's a network error on your part. 

Paste that response here so we can solve this. 

Regards, 
Félix.

**Comment by mushroomnz** [comment]
Hi Félix

This is totally my fault for not reading the email from OpenWeather, it clearly advises that the API key can take a couple hours to activate.

My apologies on this. I am all going now.

Regards

Andrew
