### ISSUE TITLE
Permanent "Requesting weather data from the server..." tooltip

### ISSUE THREAD

**Issue by enervated** [FelixdelasPozas/TrayWeather#122]
I just installed v1.22.0 and this very minor issue has carried over from the previous version: The temperature icon tooltip shows what it is supposed to, but the weather icon's tooltip always says "Requesting weather data from the server...".

I mean "always" literally. I've verified that trayweather.exe has no active connections when the tooltip is displayed.

**Comment by FelixdelasPozas** [comment]
Hi @enervated .

Thanks, I can reproduce the problem. At first both icons show the same tooltip, but then if I force an update one of them gets the "Requesting" text and the other icon shows the correct tooltip. I'll be fixed in the next release, probably before the end of the week. 

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @enervated .
It's fixed in the [latest release (1.23)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.23.0).

Regards, 
Félix.
