### ISSUE TITLE
Temperature like "-XX" doesn't fit in the tray

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#13]
Version: 1.4.2
OS: Windows 10 x64

1. Set icon type to "Current temperature"

Result: Temperature like "-XX" doesn't fit in the tray
![image](https://user-images.githubusercontent.com/4707112/102718741-1fa80500-4303-11eb-8600-9168db25644b.png)

p.s. You can use the following coordinates 74.0183476579136, 111.46908591850742 to test really low temperature

**Comment by FelixdelasPozas** [comment]
Fixed in the [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.4.3). The tray text will be smaller the longer it is. So temps like "8" will show a bigger text than "-8" (and that will be bigger than "-18"). I haven't tested all the text/icon combinations, but it should show the complete text now. 
If it doesn't work with [1.4.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.4.3) please open a new issue. 

Regards, 
Félix.

**Comment by adem4ik** [comment]
Looks fine now, thanks! 
![image](https://user-images.githubusercontent.com/4707112/102721639-774f6c00-4315-11eb-8d96-a2d176c68218.png)
