### ISSUE TITLE
Assigned icons might be wrong, or wrong interpretation of data from OpenWeather.

### ISSUE THREAD

**Issue by slizgi** [FelixdelasPozas/TrayWeather#142]
So today start snowing in my location, yet widget showing Broken Clouds icon and info despite Snowing is visible on OpenWeather website. Or they're sending wrong info via API.

**Comment by FelixdelasPozas** [comment]
Hi @slizgi . 

I suppose that the geo-localization website is giving you different coordinates than the ones your browser is giving to the OpenWeather website, that happens sometimes. That's why there is an option to use the DNS IP instead of your own IP for the geo-location. I don't think the icons are wrong because then it wouldn't be an isolated problem. If you location is wrong you can always enter them manually (you can get the coordinates of your location in google maps, for example).

Regards, 
Félix.
