### ISSUE TITLE
Weather data not loading with 1.30.0

### ISSUE THREAD

**Issue by enervated** [FelixdelasPozas/TrayWeather#168]
I just updated to TrayWeather 1.30.0 from the previous version. Now, it's stuck displaying generic icons and "Requesting weather data from the server..." in the tooltip.

Even right before updating, the prior version was working fine. Nothing else on my system has changed (firewall rules, etc.) and the "Location" tab in 1.30.0 says that my API key is still present and valid.

**Comment by FelixdelasPozas** [comment]
Hello @enervated .

Can you give me more details about the environment? 
 - Operative system 
 - version of the application: normal installation or portable

There haven't been any modification in the code, just the removal of UV data calls and related widgets. Maybe the problem is using the previous configuration data with the latest executable (there are too many combinations to test them all). Resetting the configuration might work.

Regards, 
Félix.

**Comment by enervated** [comment]
Sorry, I was logging into work and in a rush and totally forgot all that.

I'm on Windows 11 Pro 23H2
Normal installation

**Comment by enervated** [comment]
I reset the config (by deleting HKCU\Software\Felix de las Pozas Alvarez\TrayWeather with the application closed) but it didn't help.

**Comment by FelixdelasPozas** [comment]
I'm really out of ideas. I'm guessing it's the environment because it doesn't seem to be a common problem.

You can try the previous version to see if it executes correctly. The easiest way is to download the [previous portable version](https://github.com/FelixdelasPozas/TrayWeather/releases/download/1.29.1/TrayWeather_v1.29.1_Portable.7z) and extract and copy the exe to the installation directory (I suppose is "C:\Program Files\TrayWeather"). Rename the existing executable first, so we can restore it later. 

See if the previous version starts correctly, enter the configuration data (your OWM key) and check if it gets the weather and pollution data correctly. The UV tab will show an error, that's expected. If that works, and everything seems correct, then try to restore the executable of the latest version.

**Comment by enervated** [comment]
No luck, sorry. Here's what I did:

1. Closed Tray Weather.
2. Deleted "HKCU\Software\Felix de las Pozas Alvarez\TrayWeather".
3. Renamed new .EXE.
4. Added previous version .EXE as provided (1.29.1).
5. Ran 1.29.1, configured it.

It worked, except that it was drawing both the temperature and weather condition icons in the same place, which I've never seen before.

Then I closed 1.29.1, deleted it, and renamed the 1.30.1 .EXE back to the original name. Same issue as reported originally -- stuck on "Requesting weather data..."

Don't worry about it. Thanks for looking into it.

**Comment by 13regent** [comment]
I just installed version 1.30.0 and have the same message: "TrayWeather has requested the weather data for your geographic location and is still waiting for the response."  Version 1.29.1 was working fine. Using Windows 10 22H2.

**Comment by FelixdelasPozas** [comment]
Hi @enervated and @13regent .

I think I found the problem, please try the [latest release (1.30.1)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.30.1). I expect it to fix your problem.

Regards, 
Félix.

**Comment by enervated** [comment]
1.30.1 resolves the issue for me. Thank you.

**Comment by 13regent** [comment]
Version 1.30.1 works fine for me now too.

**Comment by FelixdelasPozas** [comment]
Great! Thank you both for reporting it.
