### ISSUE TITLE
GUI broken on 4K display.

### ISSUE THREAD

**Issue by michalwiglasz** [FelixdelasPozas/TrayWeather#18]
I have an 4K display and the DPI ("Scale and layout") configured to 200 %. The configuration and forecast windows are broken. If I move the window a little bit, it starts oscillating between "broken" and "ok" state, so I am eventually able to see all information.

![image](https://user-images.githubusercontent.com/478122/104091868-912eff80-5280-11eb-9d9f-03c014f1a261.png)
![104091882-9f7d1b80-5280-11eb-9f2d-77c0e61abcc5](https://user-images.githubusercontent.com/478122/104812090-280b3700-5800-11eb-9fe4-07e696f82693.png)

**Comment by FelixdelasPozas** [comment]
Hello Michal.

Sadly I'm using Qt 5,5,1 that has poor support for high dpi displays. From 5.6 the Qt toolkit replaced Webkit with Chrome, that doesn't compile in GCC for windows and I need a web browser engine for the maps part of the application. The other versions I have/use of Qt higher that 5.5.1 have no web browser because of this. And I have no plans on changing my tools to Microsoft ones. 

<b>One of the suggested fixes is to create a file named "qt.conf" in the same directory as the application (where the file "TrayWeather.exe" exists, probably "C:\Program Files\Tray Weather\\") and put these lines on it: 

    [Platforms]
    WindowsArguments = dpiawareness=0
</b>

Try it and tell me if it works as it could solve your problem in the meantime, but as I said, I don't have 4k monitors to test it. I will maintain the issue open as a reminder. 

Regards,
Felix.

**Comment by FelixdelasPozas** [comment]
Hello Michal. 

I've added some code to the [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.5.4) in attempt to fix the problem. Give it a try and tell me if it works.

**Comment by michalwiglasz** [comment]
Hi, I wasn't able to test the changes until now. The new release looks much better, although there are still some glitches.


https://user-images.githubusercontent.com/478122/104811921-11b0ab80-57ff-11eb-9094-9ff6a47e468c.mp4

![newrelease](https://user-images.githubusercontent.com/478122/104811922-15443280-57ff-11eb-9e44-132aee8a6726.png)

**Comment by michalwiglasz** [comment]
I also tried adding the qt.conf as you suggested. This solved the issue, however the app is kinda blurry - including the tray icon, which looks really bad that way. First tray icon screenshot is with qt.conf, the second one without.

![image](https://user-images.githubusercontent.com/478122/104811959-47ee2b00-57ff-11eb-9aa6-86cfb23b1666.png)
![image](https://user-images.githubusercontent.com/478122/104811971-56d4dd80-57ff-11eb-8898-13e63ebfa538.png)



https://user-images.githubusercontent.com/478122/104811946-373db500-57ff-11eb-857c-39cd7dce6a4d.mp4

![qtconf](https://user-images.githubusercontent.com/478122/104811949-3d339600-57ff-11eb-870e-6a0d514507d7.png)

**Comment by michalwiglasz** [comment]
By the way:

>  I don't have 4k monitors to test it

Maybe it could be tested by setting higher DPI on non-4k monitor? Not sure, just an idea.

**Comment by FelixdelasPozas** [comment]
> I also tried adding the qt.conf as you suggested. This solved the issue, however the app is kinda blurry - including the tray icon, which looks really bad that way. First tray icon screenshot is with qt.conf, the second one without.

Yeah, something like that was expected as the qt.conf solution lets windows do the scaling instead of the app. The documentation says it "may result in some artifacts".

While the _blurry_ version solves your problems I'll give a try at tweaking the layout to solve the problems in configuration. I'll also look at why the charts aren't scaling.

Thanks!

**Comment by FelixdelasPozas** [comment]
Try the [1.6.0 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.6.0), it might solve the problems with "too tight" layouts for your resolution. Also I've introduced some changes in the charts, so all text except for X axis should scale properly. X Axes needs more working as scaling the text just truncates it.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
No one commented after 1.6.0 release and it's been opened for about sex months. I'll close the issue as fixed.
