### ISSUE TITLE
Taskbar temperature number rounding

### ISSUE THREAD

**Issue by RopoTrop** [FelixdelasPozas/TrayWeather#20]
Hello,

Thank you for the software. Taskbar temperature number rounding is defaulting to the lower integer, for example 6.8 is rounded to 6. I guess you overlooked it? :-)

**Comment by FelixdelasPozas** [comment]
Fixed in the [1.6.1 release] (https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.6.1). The tray will show the temperature rounded to the nearest integer and the tooltip will use the temperature truncated to one decimal.

> I guess you overlooked it? :-)

Frankly I didn't think much about it because I only use the weather icon for the tray. :disappointed: 
Thanks for noticing and reporting it!

Regards,
Felix.

**Comment by RopoTrop** [comment]
Woah, that was fast. :)
I've just upgraded to the 1.6.1 release, working as intended. Thanks mate.
