### ISSUE TITLE
TrayWeather should use default icon in the task manager

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#22]
OS: Windows 10 x64
version: 1.7.0

1. Start TW
2. Open Windows' Task Manager

Result: TW uses icon from the tray depending on its settings (i.e. it shows temperature in my case) 
![image](https://user-images.githubusercontent.com/4707112/111139299-6754ca80-859a-11eb-930f-44c79058629b.png)
Expected result: TW uses default icon as in task manager's "Autorun" tab
![image](https://user-images.githubusercontent.com/4707112/111139455-94a17880-859a-11eb-9777-8bc7bc19cecf.png)

**Comment by FelixdelasPozas** [comment]
Hello Andrei.

I thinks that's a "wontfix" because has no solution, at least from a coding perspective. Raymond Chen has an [article about it](https://devblogs.microsoft.com/oldnewthing/20180301-00/?p=98135) in his **[oldnewthing](https://devblogs.microsoft.com/oldnewthing/)** blog. 
Basically as he says there are three possibilities:
- If the app has a window -> icon is the window icon.
- If the app doesn't have a window, but has a tray icon -> icon is the tray icon (TW case).
- If the app doesn't have neither window nor tray icon -> executable icon ("Autoruns" case, i suppose because the apps in that list can or can't be running, so instead of looking for the process it just goes for the executable icon)

The important thing in that article is **"There is no custom override just for Task Manager."**. So I can't set a default icon for the Task Manager list. It will use the tray icon with the visualization settings that the user selected in the configuration dialog of TW (the temperature in your case). 

Regards, 
Félix.
