### ISSUE TITLE
Размер шрифта в трее

### ISSUE THREAD

**Issue by StVol33** [FelixdelasPozas/TrayWeather#23]
Нель зя ли увеличить рамер шрифта в трее?
Значок температуры в трее очень мелкий.

**Comment by FelixdelasPozas** [comment]
Hello. This may be a problem with high dpi, ¿can you post a screenshot for reference?
I'll take a look at it for the next release, and add a configuration option if there is no way to get the tray icon size correctly. Right now the size is adjusted depending on the length of the text being shown (previous [issue](https://github.com/FelixdelasPozas/TrayWeather/issues/13)).
Thanks!

**Comment by StVol33** [comment]
Hello!
[url=http://ipic.su/img/img7/fs/screenshot2021-06-07001.1623050226.jpg][img]http://ipic.su/img/img7/fs/thumb_9d13a479550fe9f0a906328cb5edd214.1623050226.jpg[/img][/url]

**Comment by FelixdelasPozas** [comment]
![screenshot2021-06-07001 1623050226](https://user-images.githubusercontent.com/12167134/120975981-2cfe6200-c772-11eb-9a52-06cf3dcb19d1.jpg)

It's not a problem of high dpi. In fact it doesn't seem to be wrong, because a bigger font size may result in some truncation like the text in the far right of the tray (the green 10 and 16 are slightly truncated). 
Maybe I can also introduce an option in the case the user wants to override the size no matter what in the next release.
Thanks for the update!

**Comment by StVol33** [comment]
Thanks!))

**Comment by FelixdelasPozas** [comment]
Added an option to configure the size of the tray text in the [1.8.0 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.0). 

![image](https://user-images.githubusercontent.com/12167134/121608219-c8812280-ca51-11eb-8662-ce53a69cbe4b.png)

By default is 250 pixels and is the base size, it can be later modified by the application based on the length of the text to show on the tray icon. 

Regards,
Félix.
