### ISSUE TITLE
Excessive network usage when running

### ISSUE THREAD

**Issue by Fyda** [FelixdelasPozas/TrayWeather#42]
When running on Windows 10, this program appears to create excessive Internet traffic. This is regardless of anything I change in the settings, e.g. the 'Time between update requests' (for which I have tried the default "15 minutes" and also "30 minutes", with no change in this issue).

Symptoms:
- Voice chat apps, which normally have a few milliseconds of delay, suddenly have multiple seconds of delay.
- Games have unusual amounts of visible lag.
- Internet speed test results are ~20 Mbps lower in both download and upload (when compared with speed test results taken when TrayWeather is closed).

All of the above symptoms cease as soon as TrayWeather is closed.

I am wondering if this might be remedied with, perhaps, a new option in the settings to throttle the number of requests TrayWeather makes to OpenWeatherMap.

Thank you for your time.

**Comment by FelixdelasPozas** [comment]
Hi. I've looked it and apparently is the Qt library that tries to check if there are changes in network connectivity every 10 seconds. You can read about it [here](https://bugreports.qt.io/browse/QTBUG-46015). 

I've solved the problem in TrayWeather and the next release only should access the network because of:
- weather update requests.
- geo-location (only if roaming is enabled or triggered in the config dialog).
- check for application updates on github. 

Hope this solves your chat/game problems. Thanks for noticing it! I'll leave the issue open until the next release.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Test it in the [latest release 1.9.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.9.3). The fix could cause problems to other users, as new Wifi-networks or status won't be identified (maybe a problem for the "roaming" mode?

Regards,
Félix.

**Comment by Fyda** [comment]
I can confirm this issue is resolved for me in 1.9.3.

Thank you very much for your swift response!
