### ISSUE TITLE
[Suggestion] Pressure units option

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#45]
Currently TW uses `hPa` as a pressure unit. But afaik some countries use different units, so I suggest to add option similar to 'Temperature units':

- `inHg` (US/Canada)
- `mmHg` (Russia/CIS)

**Comment by FelixdelasPozas** [comment]
Currently the only conversion made in TW is temperature (ºC to Fº). Maybe I should scrap that and use OWM units options: **metric**, **imperial**, **standard** units and let the user choose. Because then we avoid having to configure individual metrics or allow weird combinations (someone could want temps in ºC but winds in feet/sec, or pressure in mBar).
I'll leave the issue open for discussion, but most probably I will choose the option of the OWM units and let the user choose a consistent metric units. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Both in standard, metric and imperial systems the [values returned](https://openweathermap.org/weather-data) by OpenWeatherMap are hectoPascals (hPa). The only changes are temperature (ºF/ºC/ºK) and wind(meters/second and miles/hour). 

Looking at the wikipedia the pressure unit in Imperial is the psi (pounds per square inch) and the precipitation units are inches per 24 hours.

I'm changing the "Temperature units" to "Measurement units" so the user can choose between Metric and Imperial (Standard is almost the same as metric and I doubt anyone will want the temperature in Kelvin). I'll add conversions for pressure (psi) and precipitation (inches) to TrayWeather, so the map legends and values are translated. But given that only 3 countries in the whole world aren't using the metric system doesn't seem necessary to add many other conversions. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik .

Working on it, it will be in the next release. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Added in [version 1.12](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.12.0).

Regards,
Félix.
