### ISSUE TITLE
TrayWeather constant low CPU use while idle in background

### ISSUE THREAD

**Issue by alystair** [FelixdelasPozas/TrayWeather#64]
I noticed consistant 0.01 - 0.02 usage by TrayWeather.exe via Process Explorer (Fantastic Sysinternals replacement for Taskman)

After restarting the app without any additional interaction it doesn't occur, so my suspicion is that UI interaction (opening and then closing the UI) triggers this behaviour.

Things that **don't** trigger it:
- hovering over the tray icons
- sleeping PC then resuming

**Comment by alystair** [comment]
Auto update notification also triggers behaviour, probably because it makes UI appear outside tray :)

**Comment by FelixdelasPozas** [comment]
Hi Alystair.

The Qt library I'm using for the user interface (and also OS events handling) has a thing called _event loop_. Its the part of the program than handles events and, so to speak, _gives_ the event to the relevant code. An event can be from the OS (asking for a repaint for example) or can be from the user (a button click event). It's constantly running and it's expected to consume some CPU because of that. If you're curious about it you can read more [here](https://wiki.qt.io/Threads_Events_QObjects#Events_and_the_event_loop).

That 0.01 it's normal and because it is so low I wouldn't worry about it. The things you mention makes the event loop work a little bit more (_triggering it_ you say) because showing a dialog involves a lot of _show events_ and _paint events_ for a lot of objects (buttons, bitmaps, text, and so on). Also, being that the normal operation mode of Qt, I can't do anything to avoid it. 

I'll close the issue because it's the normal operation of the application and not something to be corrected/fixed.

Regards, 
Félix.

**Comment by alystair** [comment]
All good, just interesting that Qt doesn't shut down when all existing windows are closed, could be re-instantiated so there's little to no background use like when application is initialized ¯\_(ツ)_/¯

**Comment by FelixdelasPozas** [comment]
Qt can't shut down, it's really receiving/managing events from the OS. If one of those events is a "double click on the tray icon", it will show the main dialog. If one of those events is a "right click on the tray icon" it will show the context menu. If one of the events is "close because the OS is shutting down" it will save settings and free its memory and quit. And so on.... it needs to be there.  ¯_(ツ)_/¯

**Comment by alystair** [comment]
Thanks for teaching me something new, I'm usually in the realm of web dev and haven't done much outside of that :)
