### ISSUE TITLE
Snow

### ISSUE THREAD

**Issue by StVol33** [FelixdelasPozas/TrayWeather#66]
Hi!
Почему в "прогнозе" и в "картах" нет данных о снеге?

**Comment by FelixdelasPozas** [comment]
Hello @StVol33.

There is snow accumulation forecast in the forecast tab (in the widgets that appear in every forecast point if you put the mouse over the point). If it doesn't appear is because the forecast is 0, same happens with rain accumulation forecast. There is no graph representation for snow, just a line for temperature and bars for rain. Maybe I can add a configuration option to use snow data and not rain for locations where snow accumulation is more important.

About the maps. Currently TrayWeather uses only the data provided by the [free version of OpenWeatherMaps](https://openweathermap.org/price), the snow forecast map will require the _advanced_ weather maps (they call it weather maps 2.0) and that requires me to pay at least 160€/month. That is something I can't afford given that TrayWeather is a free and open source application. The free version registration provides maps only for temperature, clouds, precipitation (rain), sea-level pressure and wind speed.

Regards, 
Félix.

**Comment by StVol33** [comment]
Спасибо!))
