### ISSUE TITLE
Temperature icon width might be incorrect with GUI display scaling and "Temperature text size" changed

### ISSUE THREAD

**Issue by DRSAgile** [FelixdelasPozas/TrayWeather#86]
Hi,

I have a Windows display scaling used, *as well as* "Temperature text size" changed, versus default and it seems that the temperature icon's width may not be calculated with this taken into account correctly:
![Безымянный](https://user-images.githubusercontent.com/31254856/147866947-a15da9f1-fb97-4296-9b06-81071c82fde7.png)

The "0" in "-10" gets cut.

Setting "Temperature text size" to either 250 or 300 does not seem to affect the width of the icon.

Can this be fixed?

Thanks in advance.

**Comment by FelixdelasPozas** [comment]
Hi @DRSAgile 

The "Temperature text size" field in the configuration dialog should fix that with a smaller value. By default its 250 and usually it's enough, but Windows display scaling (maybe combined with different system fonts in other Windows versions?? I'm using Win 7) may modify its appearance. 

Try smaller values to make the font smaller. If you can't find a value that solves your problem I'll try something different. Keep me updated if you can't solve it.

Regards, 
Félix.

**Comment by DRSAgile** [comment]
Indeed, a smaller text should solve this but my point was that the width of the temperature icon should probably depend on the size of the text and become bigger if the text size is chosen to be bigger.

If this could be done in some future release, then it would be great.

**Comment by DRSAgile** [comment]
The issue is that with the size setting from the screenshot I posted the temperature text is not even 1/3 tall of the height of the taskbar.

If I will have to make it smaller it would be too small.

And since the temperature in my place can hit "-20" and in this case, even that smaller size setting might still lead to part of "0" cut due to "2" being wider than "1" so I will have to make the text even yet again smaller after already making it smaller for the current case.

This is why having the width of the icon depend on the length of the text would be great: "-10" and lower temperature is already three characters instead of one-two normally.

**Comment by FelixdelasPozas** [comment]
In the release I [just published (1.16)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.0) the icon text size is automatically computed. It works for me in Win 7 but I'm not sure it will work well when "display scaling" is in use. Try it out. 

Regards,
Félix.

**Comment by CruxH** [comment]
Hi @FelixdelasPozas

I am having the same issue with Win10 at 125% scaling and TrayWeather v1.16.1:

![image](https://user-images.githubusercontent.com/7459949/148372605-bd0f09c4-72fb-4673-ba83-fa04bee26bb6.png)

The font appears bigger than with v1.15, where this issue was not observed.

**Comment by DRSAgile** [comment]
Not sure it works right since in my case I have got the font size tiny when the temperatures dropped to "-10" instead of the icon width actually increasing.

**Comment by FelixdelasPozas** [comment]
Hi @CruxH and @DRSAgile .

I've tweaked a little more the algorithm to adjust the text to the tray icon. It should look like this:
![icons](https://user-images.githubusercontent.com/12167134/148639819-622cdb8e-465a-409a-a163-b4d5ee6e940d.png)
And later I add the border to the text for greater contrast (don't take the colors into consideration I just choosed ones with good visibility). The font is already in "condensed" style to make its width smaller (thats why the 8 is touching the 2) and to allow a bigger text size. 
![32](https://user-images.githubusercontent.com/12167134/148639893-3edf3405-f045-4516-ab13-c6369a3d3c78.png)

> Not sure it works right since in my case I have got the font size tiny when the temperatures dropped to "-10" instead of the icon width actually increasing.

The icon size is fixed by windows and I cannot change its size (it will always be a square), the only thing I can do is make the font smaller so it doesn't get cut by one of its borders. 

I hope this will be fixed in the next release 1.16.2 for both high dpi and non high dpi resolutions.

Regards,
Félix.

**Comment by DRSAgile** [comment]
Thanks again, Félix.

If it is not possible to make the icon wider then, if possible, can you please make an option to switch it to a text area?

As the screenshot above shows on the example of keyboard layout language change and the wide date format there will be no issues as the width will be automatically adjustable.

In this case, the temperature will be rendered with the use of Windows-installed vector fonts/strokes/colours rather than rasterized fonts that are only allowed in the raster square icon that can not be made wider if the temperature is e.g. "-20".

What is even better is that in this case options can be added to show the "°" (U+00B0) symbol and, more importantly for some (not me personally though), "C" or "F" if they would like so since there will be no concerns for the width of the temperature area.

**Comment by FelixdelasPozas** [comment]
@DRSAgile 

> As the screenshot above shows on the examples of keyboard layout language change and the wide date format there will be no issues as the width will be automatically adjustable.

The "clock" and the "language change" widgets are from Microsoft and probably are treated as special. Don't really know if "embedded" into the taskbar code or using and API not available to the rest of applications, at least nothing is said in the [Windows SDK](https://docs.microsoft.com/en-us/windows/win32/shell/taskbar). There was a way to create something similar, called "DeskBands" but those [were deprecated in Windows 7](https://docs.microsoft.com/es-es/windows/win32/api/shobjidl_core/nn-shobjidl_core-ideskband) in favor of "Thumbnail toolbars" (or, at least, not recommended by Microsoft because I've seen some working in Win10). Other possibility is creating a custom taskbar toolbar, but I think that is really overkill for a simple weather application.

In any case Qt [does not provide](https://doc.qt.io/qt-5/qtwinextras-index.html) more facilities other than the notification tray icon. So, right now, that's the only way to show the temperature along with the weather icon. I'll just try to make it as readable as possible with the small area the tray icon provides.

Regards, 
Félix.

**Comment by DRSAgile** [comment]
Thanks for the clarification, Félix.

It is amazing how Microsoft spends years on moving the Start menu, options and applications around but still did not manage to create an API with quite a basic functionality that would have been easy to implement on their level. (Let alone many other basic things which are beyond the scope of the discussion.)

**Comment by DRSAgile** [comment]
One request though: now instead of cutting the last figure in e.g. "-10" there are significant margins that make the text way smaller than it can actually be without cutting anything from anywhere. Can those margins be switched off?

**Comment by FelixdelasPozas** [comment]
The space is necessary to paint a border around the texts, like in the previous screenshot:
![image](https://user-images.githubusercontent.com/12167134/148639893-3edf3405-f045-4516-ab13-c6369a3d3c78.png)

I'll try to make the margins as small as possible in the algorithm that computes the text size to make it as big as possible. In fact I fear the text might be too big when the temperature is in the single digits.

@CruxH , @DRSAgile  please test the [release 1.16.2](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.2) to see if it works right.

Regards, 
Félix.

**Comment by DRSAgile** [comment]
![Безымянный](https://user-images.githubusercontent.com/31254856/148655506-43772845-38c3-4d32-8a9e-10e61ea1fddd.png)

Thanks. In the new version, the font size has become ever smaller.

As seen on the screenshot, there are four unused pixel columns to the left of the "-" sign and five unused pixel columns to the right of "4" -- and that with the stroke (outline) already taken into account.

Granted, "0" is fatter than "4" so, in reality, it means there are about eight-pixel columns in total that are not used in version 1.16.2. The font size can be way bigger safely, without any threat to the stroke (outline).

**Comment by FelixdelasPozas** [comment]
@DRSAgile I don't think there is. If you use your two screenshots and put one over the other (using transparency) you can see that the "-14" is using all available columns, as the limits are where the previous "-10" got cut. 
![1](https://user-images.githubusercontent.com/12167134/148656620-7f6c752b-7b7a-49a3-b8d1-c3c0e8173e49.png)
My image is just that. 

I think that the unused columns you see are used by windows to separate tray icons from each other. 

Maybe I can use the "thin" or "extra thin" versions of the font and try to make it higher but on the other hand I can clearly see a "-14" in your previous screenshot, and that should be the main objective, to make it easy to read.

Regards,
Félix.

**Comment by DRSAgile** [comment]
Indeed, "-14" is clearly seen. My point is, that it can be seen better if the font would be taller *if* the temperature goes from 2 to 3 symbolds like >= "-10".

**Comment by FelixdelasPozas** [comment]
> My point is, that it can be seen better if the font would be taller if the temperature goes from 2 to 3 symbolds like >= "-10".

I understand your point, but I think is better to maintain coherence in all cases. That would make the font different in the 2 characters case and 3 characters case. Right now I think it's better to maintain the font characteristics ("Times New Roman" semi-condensed in all cases) as is clearly seen without having to deform it.

**Comment by DRSAgile** [comment]
By the way, there is a library for Windows 10 that does not require to do lots of manual coding to make an adjustable-width taskbar area application: [CSDeskBand](https://github.com/dsafa/CSDeskBand). But you have mentioned Qt so I am not sure if your project can be integrated to also work with a different library. And yes, you are right, MS does not recommend using anything other than built-in official APIs, so I am not suggesting anything really.

**Comment by enervated** [comment]
I just updated to 1.16.2 and noticed the tray icon text was smaller. I wanted to increase the size back to what it was, but I'm not seeing a way to change the size anymore. Has it been removed or am I just not seeing it?

![2022-01-08_20-56-51](https://user-images.githubusercontent.com/11533799/148666246-3d3b656b-03fe-4118-91b8-841fd99775b9.png)

**Comment by CruxH** [comment]
Hi @FelixdelasPozas 

The fix introduced in 1.16.2 looks good to me!

**Comment by FelixdelasPozas** [comment]
> I just updated to 1.16.2 and noticed the tray icon text was smaller. I wanted to increase the size to make it look how it looked before, but I'm not seeing a way to change the size anymore. Has it been removed or am I just not seeing it?

Hi @enervated . In the version 1.16.2 I removed the text size configuration because now the application computes the biggest font size for the icon automatically. Now the text will be as big as possible without being cropped by the icon size limits. If you have problems reading the temperature post a capture to see how I should tweak the algorithm.
Maybe you had a bigger text and some of the digits were cut by the borders. Depending on the digit it can be more or less noticeable (a 1 probably won't appear like it was cut, but a number with round borders like a 3 or a 0 certainly will).

> It looks like the configuration window is a little messed up:

I have that fixed already, it will be in the next release 1.16.3.

Regards, 
Félix.

**Comment by enervated** [comment]
I purposely didn't upload a screenshot before, because I feared the judgment would be that "It's the right size. It can't be any bigger."

But I had carefully made the font as large as it could be without having any cropping noticeable to my eye. I'm sure that there _was_ cropping, but it looked fine to me, and it was easier to read before. I am not a young person with eagle eyes anymore. I also live where the temperatures are never negative, so the added space of a "-" is irrelevant to me.

![icon](https://user-images.githubusercontent.com/11533799/148697602-cdc07cd0-0b49-4734-a6b6-8b92b5d87609.png)

**Comment by FelixdelasPozas** [comment]
Thanks for the capture, is very useful. I was thinking precisely on that, "when it can appear that the icon is not cut but it is". It's when the border of the numbers is the same color as the background. 

I'm drawing the numbers having into consideration that I'm going to draw a border later, in a color that is different from the number (for contrast) and the result is like this:
![image](https://user-images.githubusercontent.com/12167134/148639893-3edf3405-f045-4516-ab13-c6369a3d3c78.png)

But in your case the numbers are white, and that means the border will be black, also the same color of your taskbar background. So in your case it really appeared like the text was bigger and there was "no cropping" because what was being cut was the border...
Mmmm... for the next release I will try to make the border optional. It will be on by default but you'll be able to disable it in the configuration, that should allow the algorithm to draw bigger numbers in the icon.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
@enervated I've just released [version 1.17.0](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.17.0) with the option to disable the border on the temperature icon text. That will make the text bigger and it might even crop a few pixels (2 or 3) on the borders but it's not noticeable. Hope this works for you.

Regards,
Félix.

**Comment by enervated** [comment]
I've installed 1.17.0. It's nice being able to set the font size manually, but this helps a little bit. Thank you very much.

**Comment by DRSAgile** [comment]
Thanks, Félix, it works.

> I've installed 1.17.0. It's nice being able to set the font size manually, but this helps a little bit. Thank you very much.

Or to select a different, more squarish/taller font that would use more available space and hence will be bigger than this roundish one.

**Comment by FelixdelasPozas** [comment]
@enervated . In the next version you'll be able to select the font of the tray icon.

![1](https://user-images.githubusercontent.com/12167134/149659152-33abeab0-db96-4e1c-8363-04b468caaf23.png)

With the preview you'll be able to see if the selected font meets your requirements. 

![2](https://user-images.githubusercontent.com/12167134/149659155-a4d3eb19-508d-484f-9e31-fb12185909ea.png)

The next version will be released as soon as possible.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @enervated , @CruxH , @DRSAgile .

Version [1.18](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.18.0) has been released. I hope the latest version solves all the problems you've had. If no problems are reported I'll close the issue.

Regards,
Félix.

**Comment by DRSAgile** [comment]
Thanks, Félix.

I selected the "Arial Narrow" font so the digits would be even a bit taller than the default font.

It would be even better if there was a way to select a different font (for example, more squarish regular "Arial") for cases when the temperature is not three but two/one digits long. Or if the rendering of the one existing selected font could be vertically squashed in this case -- maybe a checkbox for that in some future version, if possible?

Otherwise, such a tall font is overboard if the temperature length is one-two digit.

**Comment by enervated** [comment]
Thank you! I'm using the font "Barlow Condensed" and it seems perfect on my system. I've no clue where that font came from (part of Windows I guess) but it looks better.

Thanks again!

**Comment by FelixdelasPozas** [comment]
> Thank you! I'm using the font "Barlow Condensed" and it seems perfect on my system. I've no clue where that font came from (part of Windows I guess) but it looks better.

@enervated Glad to hear!

> It would be even better if there was a way to select a different font (for example, more squarish regular "Arial") for cases when the temperature is not three but two/one digits long. Or if the rendering of the one existing selected font could be vertically squashed in this case -- maybe a checkbox for that in some future version, if possible?

@DRSAgile Yeah, I could stretch the image in the Y coordinate to fill the empty space, without changing the font. Maybe an option like "Stretch icon vertically"?
It will look like this (current on the left, stretched on the right): 
![example](https://user-images.githubusercontent.com/12167134/149805330-7cd7f63c-9bb6-446c-abbb-18d4843571a8.png)

Having different fonts for edge/corner cases is something that I will try to avoid. Maybe this option will solve your problems? With one digit it wont be stretched (as the text is taller than it is wide), only with two and three characters long texts. 

Regards, 
Félix.

**Comment by DRSAgile** [comment]
Thanks, Félix.

Stretching will also do. The only minor issue I see is the minus "-" becoming fat -- or, on the contrary, too thin in case of squashing. But I guess a fatter minus is better than a thinner one: it is more noticeable. Or this can be solved if it is possible to only stretch (or squash) digits and not the minus sign.

**Comment by FelixdelasPozas** [comment]
@DRSAgile Try the version [1.19](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.19.0). It has an option to stretch the font vertically to occupy all available space in the icon. Depending on the font the "-" may or may not become fat.
I'll close the issue, as the original problem has already been solved. Hope this release solves yours.

Regards,
Félix.

**Comment by DRSAgile** [comment]
Thanks. 

Does it work depending on whether, as we discussed, the figure is two or three digits (including the minus)? 

The stretching makes sense in the latter case since otherwise, the temperature is too tiny so we need to get the figures bigger at least vertically. 

If the temperature figure is two digits it is already big enough so stretching it just makes it look worse unnecessary.

**Comment by enervated** [comment]
My weather is always two digits (never has "-" and very rarely 100 or higher). With v1.19 I have switched to my favorite font, Tahoma, and enabled vertical stretching. I love it. It simply removes wasted space and makes it easier to read.

Thank you!

**Comment by FelixdelasPozas** [comment]
@enervated Thanks! Much appreciated!

@DRSAgile I'll look into stretching only the numbers and not the "-" but probably won't be much of a difference. As for using the stretching only with three characters and not two I think it depends on the font. I've tested cases where two and three characters are perfectly readable without stretching. Playing a little with it I think it's that more than anything else. For my tests (and the one I'm currently using) I use [Ubuntu font in bold](https://fonts.google.com/specimen/Ubuntu) and I find that the numbers look really good stretched or not. 

I'll look into it, but I suggest searching for a suitable font in [Google fonts](https://fonts.google.com) in the meantime. 

Regards,
Félix.
