### ISSUE TITLE
Temperature tray text size 

### ISSUE THREAD

**Issue by MDJ-GitHub** [FelixdelasPozas/TrayWeather#99]
Hello !, i really **love** this app but there is just one tiny thing very important i want that is not working
Being able to change Temperature text size in the tray icon (temperature & weather icon).
I'm trying to change the size but it is not working 
please implement as fast as possible thank you so much !

**Comment by FelixdelasPozas** [comment]
Hi @MDJ-GitHub .

I'll need more details about it. The size of the tray icon text is automatically computed to use all available space, it cannot be made bigger without cropping the image. Even if it seems that there are a few pixels available those are used by windows to separate icons from each other (look at a [previous issue about it](https://github.com/FelixdelasPozas/TrayWeather/issues/86)) . As the size is automatically computed there are no controls for the icon text size. Or you wanted to make it smaller?

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Sorry for the delay. In the next version you'll be able to change the icon size (up to a point).

![Clipboard02](https://user-images.githubusercontent.com/12167134/159187556-0008ea53-4689-42f3-b4bf-8de3ffb362df.png)

Regards, 
Félix.

**Comment by MDJ-GitHub** [comment]
Marvelous !!!
Thanks for your hard work !! I really appreciate it ^^

**Comment by FelixdelasPozas** [comment]
Hi @MDJ-GitHub .

Version [1.20 has been released](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.20.0). Now you'll be able to change the temperature icon size.  I'll leave the issue open until I have confirmation that your problem is solved. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
I haven't heard from this, so I'll suppose it's fixed. Closing.

Regards,
Félix.

**Comment by obuw** [comment]
The font size was also bugging me and I found this issue, so I wanted to add a comment here instead of creating a new issue, since it's a such a minor nitpick.

The font size is by default a little bigger than the other stuff in the taskbar, which looks a little out of place:
![ss0](https://user-images.githubusercontent.com/7712098/201874102-75a43601-3654-4f11-9fa9-aa7e57447568.jpg)

And if I reduce the size then the text doesn't look crisp anymore:
![ss1](https://user-images.githubusercontent.com/7712098/201874208-759c1169-40ea-4ec2-9420-1024b42c5e50.jpg)

I think being able to choose font size rather than a % scaling would have a sharper result.

Or perhaps just a different default base font size could do the trick? Looks like the default font size used by the W10 News and interests panel is Segoe UI 9pt. Of course I'm not sure if that changes in W11, or with different screen resolutions, DPI settings, etc.

I'm tempted to just edit this locally myself but I don't have a C++ development setup and my laziness is overpowering my desire to have a perfect system tray. 😛
